refactor!: Refactor to make easy improvements
yanganto/struct-patch pull request #30
Opened 2024-07-31 14:57 UTC by taorepoara

Has explained in the next comment, this refactor makes this project simpler to use and to improve: https://github.com/yanganto/struct-patch/issues/24#issuecomment-2254496376

I've based my work on the serde way of parsing AST into structs to make it more usable.

I've also changed the way I manage attributes to make it easier to add new ones.

2024-08-02 01:23 UTC, yanganto commented
Could we remove `attribute`?  and then the syntax will be simple
```
#[patch(attribute(derive(Deserialize, Debug), serde(rename = "foo"))]
```
->
```
#[patch(derive(Deserialize, Debug), serde(rename = "foo")]
```

2024-08-02 01:24 UTC, yanganto requested changes
Could we remove `attribute`?  and then the syntax will be simple
```
#[patch(attribute(derive(Deserialize, Debug), serde(rename = "foo"))]
```
->
```
#[patch(derive(Deserialize, Debug), serde(rename = "foo")]
```

2024-08-02 01:24 UTC, yanganto commented on struct-patch-derive/src/lib.rs
> +const TYPE: &str = "type";
The `TYPE` do the same thing as `NAME`, we used `patch_name` before.  It is good to drop `TYPE` and keep only `NAME` here.

2024-08-02 01:24 UTC, yanganto commented on struct-patch-derive/src/lib.rs
> +                        skip = true;
Could we return `Ok(None)` here? Such that we can remove the `skip` variable.

2024-08-02 04:56 UTC, taorepoara commented on struct-patch-derive/src/lib.rs
> +const TYPE: &str = "type";
I changed name to type here to do not confuse between the name attribute on the struc that defines the name of the patch struct and the one on the field that define the type of field in the patch struct.

Let me know what you prefer

2024-08-02 04:58 UTC, taorepoara commented on struct-patch-derive/src/lib.rs
> +                        skip = true;
I tried but we can't since we are in the `attr.parse_nested_meta` callback...

2024-08-02 05:05 UTC, taorepoara commented
> Could we remove `attribute`? and then the syntax will be simple
> 
> ```
> #[patch(attribute(derive(Deserialize, Debug), serde(rename = "foo"))]
> ```
> 
> ->
> 
> ```
> #[patch(derive(Deserialize, Debug), serde(rename = "foo")]
> ```

That's true it would be so much simple !

We just have to be careful to avoid the possibility between the attributes and the patch configuration attributes, but if there is no way to have conflict I can do that.

I also thought about this syntax (not sure if it's possible).

What do you think?

```
#[patch(
  #[derive(Deserialize, Debug)],
  #[serde(rename = "foo")]
)]
```

2024-08-02 05:25 UTC, yanganto commented on struct-patch-derive/src/lib.rs
> +const TYPE: &str = "type";
How about type_rename, I think one is good we can have a good parameter name

2024-08-02 05:40 UTC, taorepoara commented on struct-patch-derive/src/lib.rs
> +const TYPE: &str = "type";
I was not found of the type highlight two 😅

I think that one word is better, so I'll keep name like you suggested in first comment 😉

2024-08-02 05:44 UTC, yanganto commented
> ```
> #[patch(
>   #[derive(Deserialize, Debug)]
>   #[serde(rename = "foo")]
> )]
> ```
It is good and without `,`, just parse everything between `#[` and `]` as inputs.
Such that if the developer forgot to put `,`, it will not mater.

2024-08-02 05:51 UTC, taorepoara commented
> > ```
> > #[patch(
> >   #[derive(Deserialize, Debug)]
> >   #[serde(rename = "foo")]
> > )]
> > ```
> 
> It is good and without `,`, just parse everything between `#[` and `]` as inputs. Such that if the developer forgot to put `,`, it will not mater.

Yes ok, I'll try that. This could allow code injection but it's his own code and I'll see how the formatter manage that

2024-08-02 06:03 UTC, yanganto commented on struct-patch-derive/src/lib.rs
> +const TYPE: &str = "type";
By the way, Github will do hightlight for the `type`  in macro
```rust
#[patch]
struct A {
  #[patch(type=BB)]
  field_b: B,
  #[patch(ignore)]
  field_c: C,
}
```

2024-08-02 11:44 UTC, taorepoara commented
I could not implement a good solution for the attribute since the [`parse_nested_meta`](https://github.com/taorepoara/struct-patch/blob/cff660f645611e99669d9df5cf358c5c74318f59/struct-patch-derive/src/lib.rs#L194) try to parse the sub attributes names to Iden which fails on `#` character.

This could be managed with more low level parsing but could not made it this morning.

I can look at that but only in a few days. I let the `attribute` for now.

2024-08-05 11:17 UTC, yanganto approved these changes

2024-08-05 11:18 UTC, yanganto commented
Hi @taorepoara, looks good to me.
Is there anything you want to refactor in the PR?

2024-08-05 12:02 UTC, taorepoara commented
> Hi @taorepoara, it looks good to me. Is there still anything you want to refactor in the PR?

No, that all for this one. I'm working on another PR for other features and I'll try to implement the `#[patch(#[my-attribute])]` syntax later in another PR.

2024-08-05 12:28 UTC, merged