feat: Implement patch for some basic types and new from_patch attribute
yanganto/struct-patch pull request #31
Opened 2024-08-07 10:17 UTC by taorepoara

In order to ease the use of standard types like `Box` and `Option` I created default implementation of the `Patch`  trait for them.

Each type as is own feature:
- `Box`: `box`
- `Option`: `option`

I also add a `from_patch` attribute to implement `From` of the generated patch struct for the main struct.

2024-08-08 03:29 UTC, yanganto requested changes
The `into` transition from patch to instance will confuse some scenarios.
The real behavior is `patch_on_default` but not `into`

If the default is not empty, it will confuse, for example:

```rust

/// In s.rs defined S
#[derive(Patch)]
struct S {
  a: usize,
  b: usize,
}

impl Default for S {
  fn default() -> Self {
    S {
      a: 100,
      b: 0,
    }
  }
}

/// In another file using S
use s::*;

let patch = SPatch {
  a: None,
  b: Some(2),
}

let patched_s = patch.into();
/// It is not straightforward, 
/// especially in big projects with a lot of developers
///  S { a:100, b: 2, }
```

I avoided implementing `From` trait in this crate because it will easily be misleading.  Besides, the `from` feature will need `Default` trait, and `from` is in the default features of this crate, so it will reduce the usability of this crate.

Also, I think the `patch_on_default` is still misleading, the following way is good enough and easier to read for another developer. 
```rust
let patched_s = S::default().apply(patch);
```
Is it possible to remove the `from` feature?
What do you think?  I believe less is more.  Syntax sugar should fit the needs exactly and save time.

2024-08-08 06:18 UTC, taorepoara commented on struct-patch/examples/instance.rs
> +    let mut patch: ItemPatch = Item::new_empty_patch();
Yes, the type is now necessary when the std features are enable since `ItemPatch` is one a the patch for `Item`, but `Box<ItemPatch>` is one two.

2024-08-08 06:19 UTC, taorepoara commented on struct-patch/examples/patch-attr.rs
> +    let patch: ItemPatch = Item::new_empty_patch();
The type is now necessary when the std features are enable

2024-08-08 06:19 UTC, taorepoara commented on struct-patch/examples/status.rs
> +    let mut patch: ItemPatch = Item::new_empty_patch();
The type is now necessary when the std features are enable

2024-08-08 06:20 UTC, taorepoara commented on struct-patch/examples/rename-patch-struct.rs
> +    let patch: ItemOverlay = Item::new_empty_patch();
The type is now necessary when the std features are enable

2024-08-08 06:33 UTC, taorepoara commented
The `From` is necessary for the [`Option` implementation](https://github.com/taorepoara/struct-patch/blob/f07667fd4b99ab84eb8226c836f5151e47640046/struct-patch/src/std.rs#L38).

IMO to create a main struct from his patch, the `From` trait this the best solution.

> and from is in the default features of this crate, so it will reduce the usability of this crate

`from` is not in the default feature and event more it's only enabled by a specific attribute. The `From` can be manually implemented.

I can move the `from` feature in another PR if you prefer but it is pretty useful when using `Option`.
I also can rename the feature  `from_default` or `from_patch`.

Let me know :smiley:

2024-08-08 07:02 UTC, taorepoara commented
By the way, I use this implementations in one repo of mine: https://github.com/lenra-io/dofigen/blob/180-extends-files/src/dofigen_struct.rs

2024-08-08 08:01 UTC, yanganto commented
> The `From` is necessary for the [`Option` implementation](https://github.com/taorepoara/struct-patch/blob/f07667fd4b99ab84eb8226c836f5151e47640046/struct-patch/src/std.rs#L38).

No, it is not necessary, you can do it by default like you do in [from](
https://github.com/taorepoara/struct-patch/blob/f07667fd4b99ab84eb8226c836f5151e47640046/struct-patch-derive/src/lib.rs#L171-L173)
```rust
fn from(patch: #name #generics) -> Self {
    let mut s = Self::default();
    s.apply(patch);
    s
}
```
First, it is better to let others know this is from default and then `apply` the patch.
Second, the `option` feature only requires the `Default` impl not `From` impl.  
Less dependency is better, and please doc on this, such that others can easily know what they need to implement `Default` to use `option`.

---

> I can move the `from` feature in another PR if you prefer but it is pretty useful when using `Option`. I also can rename the feature `from_default` or `from_patch`.
We can split and merge `std` without `from`.

Renaming the feature does not help, I still think `.into()` is not a good thing here.
The behavior is patched on the default instance, and the following is still one line with just several chars longer.
```rust
let patched_s = S::default().apply(patch);  // No `from` trait
let patched_s: S = patch.into();            // With `from` trait
```
It is not straightforward to use `into()` here for me. 
If you insist it is straightforward, we can use another PR on `From` trait to think about this.

---

By the way, why do people using the `option` feature tend to use the `box` feature at the same time?
Could we drop `std` feature?  Not only it is unclear on the feature name, but also `option` and `box` features are not strongly related to be a group feature.

2024-08-08 10:32 UTC, taorepoara commented
> First, it is better to let others know this is from default and then `apply` the patch.
> Second, the `option` feature only requires the `Default` impl not `From` impl.
> Less dependency is better, and please doc on this, such that others can easily know what they need to implement `Default` to use `option`.

The `Default` and `From` traits are both in the Rust core lib, so I don't think that it changes the number of depedencies, isn't it ? They are both managed by the `std`.

If it's not, I think it's cleaner to keep `From` instead of `Default`.
Using `From` instead of `Default` let the user define a custom way to transform the patch into the original struct.
In my understanding of the Rust language, this is the purpose of the `From`/`Into`.
Using the `Default` is a workaround that works only with this lib.

Keeping both of them would let the dev have different behaviors for the two of them.

> If you insist it is straightforward, we can use another PR on From trait to think about this

Ok, I'll move this in another PR.

> Less dependency is better, and please doc on this, such that others can easily know what they need to implement Default to use option.

Here is the compile error when it's not satisfied: `the trait bound \`dofigen_struct::Stage: From<StagePatch>\` is not satisfied`

But I'll add some docs, it's always better to add docs, sorry I often forget ^^

> By the way, why do people using the option feature tend to use the box feature at the same time?
> Could we drop std feature? Not only it is unclear on the feature name, but also option and box features are not strongly related to be a group feature.

I created the `std` feature to enable all the features linked to the std lib. For now there is only `box` and `option`, but I'm thinking of implementing `Patch` for other std types like HashMap and other since they only can be implemented into your repo.
I can remove it if you prefer adding them one by one.

2024-08-08 10:57 UTC, taorepoara commented
By the way, this does not work since the `apply` function does not return value: `let patched_s = S::default().apply(patch);`

2024-08-09 06:37 UTC, yanganto commented
> By the way, this does not work since the `apply` function does not return value: `let patched_s = S::default().apply(patch);`

Okay, my bad, I did not carefully review the previous PR, so I forgot the interface changed.
It may be the time to implement `Add`
```rust
impl ops::Add<SPatch> for S {
    type Output = S;

    fn add(self, _rhs: SPatch) -> S {
       ...
    }
}
```

Such that we can have
```
let patched_s = S::default() + patch;
```
It will be clear and short in one line.

2024-08-09 07:45 UTC, taorepoara commented
> It may be the time to implement `Add`

Nice ! 

I'll try to implement it. I'll do it in another feature, you'll tell me if we do it as default or not :smiley:

2024-08-09 09:06 UTC, yanganto commented
> > It may be the time to implement `Add`
> 
> Nice !
> 
> I'll try to implement it. I'll do it in another feature, you'll tell me if we do it as default or not 😃

If the `Add` is good, do you like this?
```rust
impl<T, P> Patch<Option<P>> for Option<T>
where
    T: Patch<P> + Default,
{
    fn apply(&mut self, patch: Option<P>) {
        if let Some(patch) = patch {
            if let Some(self_) = self {
                self_.apply(patch);
            } else {
                *self = Some(T::default() + patch);
            }
        } else {
            *self = None;
        }
    }
}
```

And we need `#[cfg(feature = "option")]` condition for `impl ops::Add<P> for T `  but not `impl ops::Add<P> for Option<T>`.

Let `option` be dependent on `Default` not `From`, so the feature works much independently because implementation of `Default` is easier than `Form` for a user.  Besides, the user does not need to implement something around these types inside the macro if the user uses `option` only.

This also fits your use case.

I know this implementation will be harder than you originally proposed, but I still try to avoid using `.into()` inside of the macro, it will be nice if others possibly want to join the project. :pray:

If this is good, could we let `Add` feature go in before the `Box` and `Option`, because the overall implementations in the repo will be much easier to read and let people know how it works.
Please let me know if this looks good from your end. :smile:

2024-08-09 10:27 UTC, taorepoara commented
> I know this implementation will be harder than you originally proposed, but I still try to avoid using `.into()` inside of the macro, it will be nice if others possibly want to join the project. 🙏

It's not harder to implement with `Default`, but IMO the use of `From` instead of `Default` is still the best solution since `Default` is for another purpose.

Using `From` for `Option` does not need to use `into()` inside the macro, and there is no `into()` in the current version of the macro (there were in my first implementation before understanding that a problem was coming from somewhere else).

I'll squash the commits to make it cleaner.

> If this is good, could we let Add feature go in before the Box and Option, because the overall implementations in the repo will be much easier to read and let people know how it works.

Ok, I'll create a specific PR for that :smiley:

2024-08-09 12:52 UTC, yanganto commented on struct-patch/examples/instance.rs
> +    let mut patch: ItemPatch = Item::new_empty_patch();
Okay, I got this.  Thanks.

2024-08-09 12:56 UTC, yanganto approved these changes

2024-08-09 13:00 UTC, yanganto commented on README.md
> +    `T` also needs to implement `From<P>`.
```suggestion
    `T` also needs to implement `From<P>`(ex: `From<TPatch>` if you do not rename it).
```

Could we do this,  I think this will make life easier.

2024-08-09 13:56 UTC, taorepoara commented
> If we `patch` on a `None`, should we get `None` here or an `instance` from the `patch`? Like the following PR, and it seems good with the tests.

IMO the better solution is to have an instance from the patch and that's why we need the `From`.

## Example

Here is a basic use case that might be clearer.

```rust
struct User {
  name: String,
  address: Option<Address>,
}

struct Address {
  street: Option<String>,
  country: String,
}
```

If we have an initial user like this:

```rust
let user = User {
  name: "Thomas",
  address: None,
}
```

If we want to patch the user to set his address (fully or partially) with the next patch:

```rust
let patch = UserPatch {
  address: Some(Some(AddressPatch {
    country: Some("France"),
    street: None,
  }))
}
```

We need to define it from the `None` value in the main struct.
Here is the patch result this way:

```rust
User {
  name: "Thomas",
  address: Some(Address {
    street: None,
    country: "France",
  }),
}
```

If we don't, the address won't ever be defined from a patch.

Hope it's clearer.

2024-08-09 14:26 UTC, yanganto requested changes
Hi,
Please give an example under examples.
Let will be 100% clear, and good for other's with the same use case.

2024-08-12 08:01 UTC, yanganto commented
Hi @taorepoara ,
You can use `git add -f` to add the example.  The `.gitignore` about examples helps you to test the example in different branches. Sorry for the inconvenience.

2024-08-12 08:42 UTC, yanganto commented
Can we do this in the test? 
Such that we do not need a lot of `#[cfg(feature)]` and easier to read.

```rust
#[cfg(feature = "option")]
fn main() {
...
}
#[cfg(not(feature = "option"))]
fn main() { }
```
And put the `#[cfg(feature = "option")]` on the struct, not fields, if these are not inside the main.

Could you remove the `option` example in the no default feature set of CI? 
We have nothing meaningful to test with this condition, but it still takes time.

2024-08-12 08:44 UTC, yanganto requested changes

2024-08-12 08:44 UTC, yanganto commented on .github/workflows/test.yml
> +          nix develop -c cargo run --no-default-features --example option
```suggestion
```

2024-08-12 08:44 UTC, yanganto commented on struct-patch/examples/option.rs
> +fn main() {
```suggestion
#[cfg_attr(feature = "option")]
fn main() {
```

2024-08-12 22:34 UTC, yanganto approved these changes

2024-08-12 22:34 UTC, merged